### ISSUE TITLE
AppImage doesn't contain QML files

### ISSUE THREAD

**Issue by starius** [futrnostr/futr#34] opened 2024-10-13 14:17 UTC
I built the app and the AppImage and tried to run AppImage on another machine. It failed:

```
$ futr-x86_64.AppImage 

(futr:1472): Gdk-CRITICAL **: 10:06:23.484: gdk_atom_intern: assertion 'atom_name != NULL' failed

(futr:1472): Gdk-CRITICAL **: 10:06:23.485: gdk_atom_intern: assertion 'atom_name != NULL' failed
HsQML: qrc:/qml/main.qml:4:1: Type App unavailable
HsQML: qrc:/qml/content/App.qml:4:1: module "QtQuick.Controls.Material" is not installed
HsQML: qrc:/qml/content/App.qml:3:1: module "QtQuick.Controls" is not installed
HsQML: qrc:/qml/content/App.qml:2:1: module "QtQuick.Window" is not installed
HsQML: qrc:/qml/content/App.qml:4:1: module "QtQuick.Controls.Material" is not installed
HsQML: qrc:/qml/content/App.qml:3:1: module "QtQuick.Controls" is not installed
HsQML: qrc:/qml/content/App.qml:2:1: module "QtQuick.Window" is not installed
HsQML: qrc:/qml/content/App.qml:4:1: module "QtQuick.Controls.Material" is not installed
HsQML: qrc:/qml/content/App.qml:3:1: module "QtQuick.Controls" is not installed
HsQML: qrc:/qml/content/App.qml:2:1: module "QtQuick.Window" is not installed
```

**Comment by prolic** [comment] 2024-10-13 17:45
You can check the binary with ldd and see what it's linking against. App
image should include qt lib bindings into the binary.

**Comment by prolic** [comment] 2024-10-13 22:29
Testing on my machine gives me:
```bash
ldd futr  | grep Qt
	libQt5Widgets.so.5 => /home/sasa/code/futr/futr.AppDir/usr/bin/./../lib/libQt5Widgets.so.5 (0x00007f0028069000)
	libQt5Quick.so.5 => /home/sasa/code/futr/futr.AppDir/usr/bin/./../lib/libQt5Quick.so.5 (0x00007f0027a88000)
	libQt5Gui.so.5 => /home/sasa/code/futr/futr.AppDir/usr/bin/./../lib/libQt5Gui.so.5 (0x00007f0027338000)
	libQt5QmlModels.so.5 => /home/sasa/code/futr/futr.AppDir/usr/bin/./../lib/libQt5QmlModels.so.5 (0x00007f00272a3000)
	libQt5Qml.so.5 => /home/sasa/code/futr/futr.AppDir/usr/bin/./../lib/libQt5Qml.so.5 (0x00007f0026dde000)
	libQt5Network.so.5 => /home/sasa/code/futr/futr.AppDir/usr/bin/./../lib/libQt5Network.so.5 (0x00007f0026c13000)
	libQt5Core.so.5 => /home/sasa/code/futr/futr.AppDir/usr/bin/./../lib/libQt5Core.so.5 (0x00007f002666c000)
```

So linking wasn't a problem for me.

**Comment by starius** [comment] 2024-10-13 23:54
I think the issue is not in .so files, but in .qml files.

**Comment by prolic** [comment] 2024-10-14 00:04
I can send you a binary created from my computer to try if you want.

**Comment by starius** [comment] 2024-10-14 00:06
Please, send it.

**Comment by prolic** [comment] 2024-10-14 01:46
https://drive.google.com/file/d/1ROIxzwWVnmAy60IQCrFFPSrF3ilq952J/view?usp=sharing

39MB

**Comment by starius** [comment] 2024-10-14 04:14
Access requested

> https://drive.google.com/file/d/1ROIxzwWVnmAy60IQCrFFPSrF3ilq952J/view?usp=sharing
> 
> 39MB

**Comment by starius** [comment] 2024-10-14 12:38
The AppImage from the link fails to start:

```
futr-x86_64.AppImage

(futr:1751): Gdk-CRITICAL **: 09:38:12.053: gdk_atom_intern: assertion 'atom_name != NULL' failed

(futr:1751): Gdk-CRITICAL **: 09:38:12.054: gdk_atom_intern: assertion 'atom_name != NULL' failed
Cannot mix incompatible Qt library (5.15.8) with this library (5.15.3)
Aborted
```

**Comment by prolic** [comment] 2024-10-14 14:25
export LD_LIBRARY_PATH=""
./futr-x86_64.AppImage

Or

export QT_PLUGIN_PATH=""
./futr-x86_64.AppImage

Can you try?

**Comment by starius** [comment] 2024-10-14 17:11
I tried both commands. It is still failing, with the same error message.

**Comment by prolic** [comment] 2024-10-14 17:26
./futr-x86_64.AppImage --no-sandbox

Can you try this? It seems to be a problem that you have already qt
installed, but a different minor version than in the app. We need to tell
it to ignore your installation and use what's included in the binary.

**Comment by starius** [comment] 2024-10-14 17:31
`--no-sandbox` also didn't change the outcome.

**Comment by prolic** [comment] 2024-10-14 17:49
https://bugs.kde.org/show_bug.cgi?id=490704

Damn, remote debugging is hard 😂

Let me know if that helps.

Not really a solution, but you can use app image tool, extract the image,
replace qt lib with what you have on your system and pack the app image
again.
But that's nothing I can propose as general solution.

**Comment by prolic** [comment] 2024-10-14 18:13
@starius I'm uploading a new app image right now, will share the link in a second. Can you try this one instead?

**Comment by prolic** [comment] 2024-10-14 18:16
https://drive.google.com/file/d/1CbQlQQn-dPxZ6L9d6djAxrQKaJxT_nFn/view?usp=drive_link

@starius can you test this?

**Comment by starius** [comment] 2024-10-14 18:59
> https://drive.google.com/file/d/1CbQlQQn-dPxZ6L9d6djAxrQKaJxT_nFn/view?usp=drive_link
> 
> @starius can you test this?

This image works the same.

**Comment by prolic** [comment] 2024-10-14 19:04
@starius again with the same message

```bash
futr-x86_64.AppImage

(futr:1751): Gdk-CRITICAL **: 09:38:12.053: gdk_atom_intern: assertion 'atom_name != NULL' failed

(futr:1751): Gdk-CRITICAL **: 09:38:12.054: gdk_atom_intern: assertion 'atom_name != NULL' failed
Cannot mix incompatible Qt library (5.15.8) with this library (5.15.3)
Aborted
```
?

**Comment by starius** [comment] 2024-10-14 19:07
```
$ futr-x86_64\(1\).AppImage --no-sandbox

(futr:1760): Gdk-CRITICAL **: 15:59:35.818: gdk_atom_intern: assertion 'atom_name != NULL' failed

(futr:1760): Gdk-CRITICAL **: 15:59:35.818: gdk_atom_intern: assertion 'atom_name != NULL' failed
Cannot mix incompatible Qt library (5.15.8) with this library (5.15.3)
Aborted
```

**Comment by starius** [comment] 2024-10-14 19:27
```
~/squashfs-root$ cat AppRun 
#!/bin/bash

# Get the directory of the AppRun script
HERE="$(dirname "$(readlink -f "${0}")")"

# Preload the AppImage's Qt libraries to override system ones
export LD_PRELOAD="$HERE/usr/lib/libQt5Core.so.5:\
$HERE/usr/lib/libQt5Gui.so.5:\
$HERE/usr/lib/libQt5Network.so.5:\
$HERE/usr/lib/libQt5Qml.so.5:\
$HERE/usr/lib/libQt5QmlModels.so.5:\
$HERE/usr/lib/libQt5Quick.so.5:\
$HERE/usr/lib/libQt5Widgets.so.5"

# Run the original command
exec "${HERE}/usr/bin/futr" "$@"
```

```
~/squashfs-root$ ldd usr/bin/futr | grep Qt
	libQt5Widgets.so.5 => /home/user/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5 (0x00007e5c6a600000)
	libQt5Quick.so.5 => /home/user/squashfs-root/usr/bin/../lib/libQt5Quick.so.5 (0x00007e5c6a000000)
	libQt5Gui.so.5 => /home/user/squashfs-root/usr/bin/../lib/libQt5Gui.so.5 (0x00007e5c69800000)
	libQt5QmlModels.so.5 => /home/user/squashfs-root/usr/bin/../lib/libQt5QmlModels.so.5 (0x00007e5c6ad6b000)
	libQt5Qml.so.5 => /home/user/squashfs-root/usr/bin/../lib/libQt5Qml.so.5 (0x00007e5c69200000)
	libQt5Network.so.5 => /home/user/squashfs-root/usr/bin/../lib/libQt5Network.so.5 (0x00007e5c69035000)
	libQt5Core.so.5 => /home/user/squashfs-root/usr/bin/../lib/libQt5Core.so.5 (0x00007e5c68a00000)
```

**Comment by prolic** [comment] 2024-10-14 19:30
Alright, I grab a Debian 12 docker image and try to reproduce myself.

**Comment by starius** [comment] 2024-10-14 19:33
I tried to run it with `strace`:
```
strace -f -o /tmp/strace.log ./AppRun
(futr:2260): Gdk-CRITICAL **: 16:30:09.569: gdk_atom_intern: assertion 'atom_name != NULL' failed

(futr:2260): Gdk-CRITICAL **: 16:30:09.575: gdk_atom_intern: assertion 'atom_name != NULL' failed
Cannot mix incompatible Qt library (5.15.8) with this library (5.15.3)
Aborted
```

```
$ grep /usr/lib/x86_64-linux-gnu/qt5 /tmp/strace.log | grep openat
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqwayland-egl.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqwayland-generic.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqwayland-xcomposite-egl.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqwayland-xcomposite-glx.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so.avx2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so", O_RDONLY|O_CLOEXEC) = 11
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 14
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so", O_RDONLY|O_CLOEXEC) = 14
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so.avx2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so", O_RDONLY|O_CLOEXEC) = 14
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 17
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 17
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 17
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so.avx2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
2260  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 17
```

It seems to load some stuff from system installation of Qt.

**Comment by prolic** [comment] 2024-10-14 19:34
I'm pretty sure, if you uninstall Qt from your system, this works again. But there must be way to bypass this. I'm trying to find something on Google and test on Debian 12 in docker.

**Comment by starius** [comment] 2024-10-14 19:46
I uninstalled everything with "qt" in name:

```
sudo aptitude remove ~i~nqt
The following packages will be REMOVED:
  fonts-font-awesome{u} keepassxc{a} libbotan-2-19{u} libmd4c0{u} libpcre2-16-0{u} libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5{u} libqt5gui5 libqt5help5{u} libqt5network5 
  libqt5printsupport5{u} libqt5qml5 libqt5qmlmodels5{u} libqt5quick5 libqt5sql5 libqt5sql5-sqlite libqt5svg5 libqt5test5{u} libqt5waylandclient5{u} libqt5waylandcompositor5{u} libqt5widgets5 
  libqt5x11extras5 libqt5xml5 librnp0{u} libtorrent-rasterbar2.0{u} libtspi1{u} libu2f-udev{u} libwpe-1.0-1{u} libwpebackend-fdo-1.0-1{u} libxcb-xinerama0{u} libxcb-xinput0{u} libzxcvbn0{u} python3-pyqt5 
  python3-pyqt5.sip python3-qrtools{u} python3-zbar{u} qbittorrent{a} qt5-gtk-platformtheme qtqr qttranslations5-l10n qtwayland5
```

The appimage is failing, but the error message is different:

```
futr-x86_64\(1\).AppImage --no-sandbox
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted
```

**Comment by prolic** [comment] 2024-10-14 19:56
https://drive.google.com/file/d/1rmTZ4icZEh_m05TJ53yrq3I-B9rkUBTx/view?usp=drive_link

can you try this? build with an alternative appimage tool

**Comment by prolic** [comment] 2024-10-14 20:11
In the meantime, Debian 12 is now building locally in docker. I keep you posted.

**Comment by prolic** [comment] 2024-10-14 20:20
oh nice, that's actually not too bad, one second

**Comment by prolic** [comment] 2024-10-14 21:00
Have you tried the docker container, yet? I'm building new app images locally and try to fix this problem.

**Comment by prolic** [comment] 2024-10-15 01:06
@starius I prepared a flatpak to test - I could verify I was able to run this in a different computer without any qt and stuff installed.

To install flatpak:

```bash
sudo apt-get install flatpak
sudo apt install gnome-software-plugin-flatpak (optional)
sudo apt install plasma-discover-backend-flatpak (optional)
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
```

Install futr:

```bash
flatpak install flathub org.kde.Platform//5.15-23.08
flatpak install --user futr.flatpak
```

Start the app:

```bash
flatpak run com.futrnostr.futr
```

`futr.flatpak` file is available here https://drive.google.com/file/d/1RY5_8ykrnjFKUxFyawHUZeCnAjdFMv8Q/view?usp=drive_link

**Comment by prolic** [comment] 2024-10-15 01:07
If this works for you as well, then I can dig deeper on how to possibly remove kde platform dependency and push the build script.

**Comment by prolic** [comment] 2024-10-15 01:09
Note: try without `flatpak install flathub org.kde.Platform//5.15-23.08` - flatpak install should actually download it for you if required.

**Comment by starius** [comment] 2024-10-15 12:29
It works!

Without `flatpak install flathub org.kde.Platform//5.15-23.08` it didn't work:
```
$ flatpak install --user futr.flatpak

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/user/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: The application com.futrnostr.futr/x86_64/master requires the runtime org.kde.Platform/x86_64/5.15-23.08 which was not found
```

**Comment by prolic** [comment] 2024-10-15 16:06
Success! Glad it works. I'll push the code to generate the flatpak today.

**Comment by prolic** [comment] 2024-10-15 22:19
@starius can you try this one real quick?

https://drive.google.com/file/d/1B6gTMCybO80XsM2KZgwlAGiDZcy4r2NS/view?usp=drive_link

**Comment by prolic** [comment] 2024-10-15 22:48
one more: https://drive.google.com/file/d/12OwNaISnyF4BZp6l7CDd2GNWSY6Kvaxp/view?usp=drive_link

**Comment by prolic** [comment] 2024-10-15 23:10
closing this one.

I created a new ticket for app images, in case someone wants to work on it: https://github.com/futrnostr/futr/issues/36

bbd1f24544801c8b23de9edb91adc0100c7d1cbe introduces flatpak builder instead, tested on three different machines it seems to work good so far.

**Closed by prolic** 2024-10-15 23:10 UTC
